### ISSUE TITLE
To handle torch.tensor and a more general usage of the boost/invs_boost functions

### ISSUE THREAD

**Issue by jaychan-hep** [hep-lbdl/hadml#6]
Modify the boost/invs_boost functions (https://github.com/hep-lbdl/hadml/blob/main/hadml/datamodules/components/utils.py#L65) to:

- handle torch.tensor besides numpy.array
- allow a more general usage
- allow to be used in the GAN model

**Comment by xju2** [comment]
#21 solved the issue.
